# Global configuration
[global]
default_verbose = false  # Enable verbose output by default
dry_run = false         # Enable dry-run mode by default

# Each backup pair defines a source/target relationship
[[backup_pairs]]
name = "root_system"
original_volume = "/"                           # Original BTRFS volume to snapshot
source = "/btrfs/btrfs-subvolumes/root"    # Source BTRFS subvolume path
target = "/backup/btrfs-subvolumes/root"   # Target backup location
retention_days = 30      # Days to keep snapshots in source
retention_count = 10     # Minimum snapshots to keep in source (larger applies)
target_retention_days = 90    # Days to keep backups in target
target_retention_count = 20   # Minimum backups to keep in target

[[backup_pairs]]
name = "home_directories"
original_volume = "/home"
source = "/btrfs/btrfs-subvolumes/home"
target = "/backup/btrfs-subvolumes/home"
retention_days = 14
retention_count = 15
target_retention_days = 60
target_retention_count = 30
